version: "3"
services:
  app:
    build: .
    environment:
      # - BACKEND=http://help.websiteos.com/websiteos/example_of_a_simple_html_page.htm
      #- BACKEND=http://data.dlll-paas-starter.pudding.paas.dlll.pulipuli.info/
      #- BACKEND=data.dlll-paas-starter.pudding.paas.dlll.pulipuli.info:80
      #- BACKEND=pudding-ThinkPad-L13-Yoga-Gen-2-Linux
      #- BACKENDS=["80,http://pudding-ThinkPad-L13-Yoga-Gen-2-Linux/"]
      - BACKENDS=["80,http://data.dlll-paas-starter.pudding.paas.dlll.pulipuli.info/","81,http://info.cern.ch/"]
      - SCALE_DOWN_WAIT=180000
      - DEPLOY_GIT_URL=https://argocd:9UpC1PMo51UxcgtGdqAA@gitlab.nccu.syntixi.dev/deploybot/argocd.git
      - BRANCH=dlll-paas-starter-pudding
      - ARGOCD_AUTH_TOKEN=eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJodms1Q2ZDanF3Vkg0U1lrIiwic2VydmVyIjoiaHR0cHM6Ly9hcmdvY2QubmNjdS5zeW50aXhpLmRldiJ9
    #volumes:
    # - "./config/nginx.conf:/etc/nginx/nginx.conf:ro"
    # - "./conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
    #- "./scaler:/dlll_paas/scaler"
    #- "./html:/dlll_paas/html"
    ports:
    - "7000:80"
    - "7001:81"
    - "8081:8081"
    - "8082:8082"
    