version: "3"
services:
  app:
    build: .
    volumes:
    # - "./config/nginx.conf:/etc/nginx/nginx.conf:ro"
    - "./conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
    - "7000:80"